# Generated by Django 2.0.4 on 2018-11-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('criaçao', models.DateField()),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.EstiloMusical')),
                ('musico', models.ManyToManyField(to='music.Musico')),
            ],
        ),
    ]
